---
name: stage-cline-gpt-image-execution-feedback
description: V2.7.1 C线 GPT Image 执行反馈。用于 T线生成中文 GPT Image 合同后，执行或准备视觉样张、预测偏差、记录实际执行回执、维护样张状态、诊断失败并生成最小局部修改合同。
---

# C线：GPT Image 执行反馈

## 渐进式读取

### 必读
- 当前 `SKILL.md`、T线唯一中文合同，以及当前可用的执行回执、样张或用户反馈。
- 不默认读取共享总控、失败分类、模板或示例。

### 按需读取路由
- 一次只允许由当前唯一未决问题触发一个来源；读取后先执行快速确认，再决定是否扩展下一项。
- 需要判断样张状态或用户确认状态：读 `_shared/visual-sample-state-rules.md` 的相关状态条目。
- 任务涉及透明前景、动画风险、Remotion失败反馈或拆层：读 `_shared/remotion-asset-handoff-rules.md` 的对应Gate。
- 已经发生可观察失败：读 `_shared/failure-diagnosis-rules.md` 中对应失败类别，不预读其他类别。
- 需要输出正式反馈卡：读 `templates/c_line_feedback_card.md`。
- 只有出现局部修改越界或定稿误称风险时，读取一个直接匹配的 example/anti-example。

### 快速确认
确认当前任务是执行准备、结果记录、失败诊断还是局部修改；再确认冻结项、可观察证据、失败类别和最小修改范围。类别已由证据支持时停止读取。

### 停止规则
输出执行/反馈合同、完成一次图像生成或提出一个用户确认 Gate 后立即停止；一次授权只覆盖当前一个产物。一次局部失败不触发 A/B/T 全链重读；只有明确定位到上游依据缺陷时才退回对应阶段。

## 本阶段的确认与写入纪律
- 抽样页选择、将使用的提示词版本和每一次图像生成是三个独立决定，必须按顺序分别确认；一次只问一个问题，当前问题未回答前不得询问下一项。
- 用户确认提示词只表示提示词内容获确认，不等于授权生图；用户确认一张样张也不等于授权下一张、下一轮或局部修改。每次生图都要取得针对该次图像产物的明确授权，完成后立即停止。
- 信息不足时先读当前 T线合同、已确认参考材料、现有回执或样张；仍不能消除的信息差才一次追问一个问题，不得把多个决策写进同一问句或相邻上下段。
- 写正式执行/反馈卡前，先说明准备生成什么、写到哪个文件、是否修改已有文件、下一步实际需要接收什么，以及哪些分析或验证记录不属于正式交付；随后只问：`是否按上述产物与交接方案执行？`
- 未获本次明确授权不得写入。不得向 S/A/B/T 文件追加，不得复制上游全文或把后续产物混入当前文件。

## 职责与边界
C线只负责 GPT Image 视觉样张的执行准备与反馈，不是多平台执行器。可使用当前环境已经提供的图像生成能力；能力不可用时只输出执行与反馈合同。不得自行接入 API、密钥、SDK 或新增依赖。

## 输入
接收 T线的中文 GPT Image 提示词合同、所选方案、可选的执行回执、已生成视觉样张或用户反馈，以及可选的局部修改请求。

## Reference Preflight
For `reference_locked_full_page`, verify every selected path exists and is readable, the user-confirmed primary reference is attached to generation, and text-only fallback is not used. Do not attach the whole folder, previous conversation images, unselected references, or failed images automatically.

The first deliverable is one complete with-text canvas generated directly by GPT Image. Strongly review the canvas ratio, panel structure, title system, information regions, image/text relationship, hierarchy, palette, and visible background reconstruction. Do not claim pixel identity.

## Text Accuracy Gate
Compare title, body, numbers, English, and punctuation against `must_show_text_verbatim`. All text is generated by GPT Image. Allow at most two local text revisions after the initial generation. Preserve the same explicit references and isolated context on every revision. Persistent mismatch is `text_generation_failure`; deterministic text overlay is forbidden.

## 执行前
始终输出偏差预测：可能漂移、用于抑制漂移的提示词结构、禁止写入图像的内容，以及必须保持的冻结项。偏差预测不是生图授权；只有抽样页和提示词版本分别确认后，才可单独询问是否执行当前一次生图。

## 模型真实性
区分 `请求模型` 与 `实际执行模型`。请求模型可为 `gpt-image-2`；实际执行模型必须来自工具或 API 的明确回执，没有回执时写 `未报告`，不得推断或伪造。

## 背景与 Alpha
完整课程视觉页默认不透明。只有素材层、抠图对象或可叠加组件明确要求 Alpha 时才使用透明背景，输出格式限 `png` 或 `webp`，并标注透明背景为预览能力；能力不可用时降级为不透明背景并记录偏差。

## 视觉样张状态
Ordinary GPT Image results use `visual_sample_generated`. A complete reference-locked with-text page that passes layout and text checks uses `full_page_candidate`. Only explicit user confirmation moves it to `final_course_visual`.

## Remotion Asset Gate
After `final_course_visual`, C-line may propose a transparent foreground for `animation_structure_risk` or accept `external_remotion_failure`. It must ask the user before execution. The confirmed final page is the only edit target.

Keep the original full canvas and top-left origin; remove only declared fixed-master regions. Preserve text, image positions, relative scale, shadows, and layout. Output real-Alpha PNG. Opaque, white, gray, or checkerboard fallback is forbidden. Allow at most two local Alpha revisions, then return `alpha_generation_failure`.

Optional title/image/body split layers require a second explicit Gate. All layers remain full-canvas; cropping to tight bounds is forbidden.

## 局部修改合同
每次局部修改必须包含修订范围、保留项、仅修改项、禁止修改项、参考依据、最小修改指令和是否需要用户确认。不得把局部修改扩张为整页重绘。

## 失败处理
先按内容、结构、美学、文字、素材、继承、范围或模型边界分类，再输出最小修改指令。一次失败不得推翻全部 A/B/T线结果。

## 输出合同
普通状态判断或缺失信息 Gate 可直接输出，不读取模板。只有需要正式执行/反馈卡时，才读取并使用 `templates/c_line_feedback_card.md`。

## 禁止事项
不得执行历史平台；不得把样张称为定稿；除非用户明确要求或 B/T线依据无法保留，否则不得整页重做。不得把确认提示词、确认抽样页或确认产物写入方案解释为生图授权。不得计算、传递或要求哈希、摘要或指纹；参考资产只沿用非哈希清单。

## 失败与退回
提示词或生产策略缺陷退回 B线；页面含义、素材权限或冻结字段冲突退回 A线；样张确认、透明前景Gate、拆层Gate或局部修订范围不清时询问用户。

## 最小示例
示例只作为已发生问题的对照证据。Remotion透明前景被错误降级为不透明时，读 `anti_examples/remotion_opaque_fallback_failure.md`；不是执行前必读项。
